[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_RUNTIME_ENV = "netlify"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 